language: node_js
node_js:
  - "8"

os:
  - linux

cache:
  directories:
    - node_modules

before_install:
  - npm install

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - npm test